"""Generate the Circular Cross scenarios: N robots on a circle, each swapping with its antipode.

Writes conf/env/circular_cross_{N}_unicycle2.yaml.

This is NOT a K-ARC benchmark. It exists to test whether a coordination mechanism generalises
or has quietly learned the open cross's shape. Open Cross and Cluttered Cross both lay robots
out in parallel rows travelling along one axis, so "which side to pass on" has a global
meaning (up or down) and neighbouring conflicts are arranged in a path. On a circle none of
that survives:

  * there are no rows, so nothing can be indexed by row parity;
  * every route runs through ONE hub, so the conflicts form a dense graph rather than a path;
  * routes point in every direction, so "sideways" is only definable per encounter, and a
    single global axis cannot separate everyone.

Congestion still comes from N alone: the circle does not grow, so more robots means less arc
between neighbours, exactly as more rows means less vertical spacing in the open cross.

    python scripts/gen_circular_cross.py            # all sizes
    python scripts/gen_circular_cross.py --n 16     # one
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ROBOT = ROOT / "conf" / "robot" / "unicycle_db.yaml"
REFERENCE = ROOT / "conf" / "env" / "open_cross_32_unicycle2.yaml"

WORLD = 17.0
MARGIN = 1.0
RADIUS = WORLD / 2 - MARGIN          # 7.5 m; the 15.0 m diameter matches open cross's traverse
SIZES = [4, 8, 16, 32]


def num(v: float) -> str:
    s = f"{v:.6g}"
    return s if ("." in s or "e" in s) else s + ".0"


def body_diameter() -> float:
    """Rotation-invariant body size: two robots closer than this can overlap at ANY heading."""
    shape = yaml.safe_load(ROBOT.read_text())["shape"]
    return math.hypot(shape["width"], shape["length"])


def arc_spacing(n: int) -> float:
    """Arc between neighbouring start points -- the congestion knob, as row spacing is there."""
    return 2 * math.pi * RADIUS / n


def agents(n: int):
    """Robot i starts at angle 2*pi*i/n and swaps with the robot opposite it.

    Heading points along the robot's own route, i.e. straight at the hub, so no robot begins
    by having to turn around. Every route is a diameter, so all n of them cross at the centre
    -- which is the whole point of the scenario.
    """
    c = WORLD / 2
    out = []
    for i in range(n):
        th = 2 * math.pi * i / n
        sx, sy = c + RADIUS * math.cos(th), c + RADIUS * math.sin(th)
        gx, gy = c - RADIUS * math.cos(th), c - RADIUS * math.sin(th)
        heading = math.atan2(gy - sy, gx - sx)
        out.append((i, sx, sy, heading, gx, gy))
    return out


def render(n: int) -> str:
    if n < 2 or n % 2:
        raise ValueError(f"N must be even and >= 2, got {n}")
    gap, body = arc_spacing(n), body_diameter()
    if gap <= body:
        raise ValueError(
            f"N={n} puts {gap:.3f} m of arc between neighbouring starts, which is not more "
            f"than the unicycle_db body diagonal {body:.3f} m -- the robots would start "
            f"overlapping. Raise RADIUS or drop this N.")

    head = f"""# @package env
# Circular Cross at N={n}: robots evenly spaced on a circle, each swapping with the robot
# diametrically opposite it. GENERATED by scripts/gen_circular_cross.py -- edit the script.
#
# NOT a K-ARC benchmark. This is a generalisation test: Open Cross and Cluttered Cross are
# both parallel rows along one axis, so a mechanism can pass them while secretly depending on
# that layout. Here there are no rows to index, every route is a diameter through a single
# hub so the conflict graph is dense rather than a path, and routes point in every direction
# so a single global "sideways" cannot separate anyone.
#
# Radius {num(RADIUS)} m, so the {num(2 * RADIUS)} m traverse matches open cross's and runtimes stay
# comparable. Arc between neighbouring starts is 2*pi*R/N = {gap:.3f} m at this N, against a
# {body:.3f} m body diagonal.
#
# Robot, reward, dt, max_steps and the goal test are inherited from
# conf/env/open_cross_32_unicycle2.yaml so the only thing that differs is the layout.
_name_: circular_cross_{n}_unicycle2

world_size: {num(WORLD)}
dt: 0.1
max_steps: 1300
goal_radius: 0.2

reward:
  reach: 50.0
  collision: -2.0
  step_penalty: -0.01
  shaping_scale: 4.0
  effort_penalty: -0.002
  omega_penalty: -0.04

omega_max_override: null
terminate_on_collision: false
require_stop_at_goal: true
stop_speed: 0.4

obstacles: []
agents:
"""
    body_lines = []
    for i, sx, sy, th, gx, gy in agents(n):
        body_lines.append(
            f"  - id: agent_{i}\n"
            f"    start: [{num(sx)}, {num(sy)}, {num(th)}, 0.0, 0.0]\n"
            f"    goal:  [{num(gx)}, {num(gy)}, {num(th)}, 0.0, 0.0]\n"
            f"    robot: unicycle_db\n")
    return head + "".join(body_lines)


def check() -> None:
    """Invariants that must hold at every N, asserted rather than assumed."""
    ref = yaml.safe_load(REFERENCE.read_text())
    body = body_diameter()
    for n in SIZES:
        doc = yaml.safe_load(render(n))
        assert len(doc["agents"]) == n, n
        for key in ("world_size", "dt", "max_steps", "goal_radius", "reward"):
            assert doc[key] == ref[key], (n, key)
        for a in doc["agents"]:
            sx, sy = a["start"][:2]
            gx, gy = a["goal"][:2]
            # Coordinates are written through `num`, which keeps 6 significant digits, so
            # these compare at the precision the FILE actually carries, not at float
            # precision -- the values are re-read from the rendered YAML.
            tol = 1e-3
            # start and goal are antipodal about the world centre
            assert abs((sx + gx) / 2 - WORLD / 2) < tol, a["id"]
            assert abs((sy + gy) / 2 - WORLD / 2) < tol, a["id"]
            # the traverse is the diameter, and it clears the walls
            assert abs(math.hypot(gx - sx, gy - sy) - 2 * RADIUS) < tol, a["id"]
            for v in (sx, sy, gx, gy):
                assert MARGIN - 1e-9 <= v <= WORLD - MARGIN + 1e-9, a["id"]
        # no two robots start overlapping
        pts = [(a["start"][0], a["start"][1]) for a in doc["agents"]]
        worst = min(math.dist(p, q) for i, p in enumerate(pts) for q in pts[i + 1:])
        assert worst > body, (n, worst, body)
    print(f"check ok: {SIZES}, tightest start gap > body diagonal {body:.3f} m")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--n", type=int, default=None, help=f"one size; default all of {SIZES}")
    ap.add_argument("--out-dir", type=Path, default=ROOT / "conf" / "env")
    ap.add_argument("--check", action="store_true", help="run invariants and write nothing")
    args = ap.parse_args()

    if args.check:
        check()
        return
    check()
    for n in ([args.n] if args.n else SIZES):
        path = args.out_dir / f"circular_cross_{n}_unicycle2.yaml"
        path.write_text(render(n))
        print(f"wrote {path}  (arc between neighbours {arc_spacing(n):.3f} m)")


if __name__ == "__main__":
    main()
